package com.bodish.niyoj

import android.content.Context
import org.json.JSONObject

/**
 * The shell we send to servers, read verbatim from assets/scripts.json, which is
 * generated by `python deployer.py --scripts`. Desktop and phone therefore run
 * byte-identical scripts, and deployer.py's selftest fails if this copy is stale.
 */
object Scripts {
    private lateinit var all: JSONObject

    fun load(ctx: Context) {
        if (::all.isInitialized) return
        all = JSONObject(ctx.assets.open("scripts.json").bufferedReader().use { it.readText() })
    }

    val scan: String get() = all.getString("scan")
    val probe: String get() = all.getString("probe")

    fun deploy(app: JSONObject): String {
        app.optString("cmd").let { if (it.isNotEmpty()) return it }
        return all.getString("deploy")
            .replace("{dir}", app.optString("dir"))
            .replace("{repo}", app.optString("repo"))
            .replace("{branch}", app.optString("branch").ifEmpty { "main" })
    }

    fun prep(dest: String): String = all.getString("prep").replace("{dest}", dest)

    fun swap(dest: String): String = all.getString("swap").replace("{dest}", dest)

    // Same guard as deployer.py: the key is single-quoted into a remote shell, so
    // a quote anywhere in it would be an injection.
    private val PUB = Regex(
        "^(?:ssh-ed25519|ssh-rsa|ecdsa-sha2-nistp\\d+) [A-Za-z0-9+/=]+(?: [^\\r\\n'\"]*)?$"
    )

    fun authz(pub: String): String {
        val key = pub.trim()
        require(PUB.matches(key)) { "that is not an OpenSSH public key" }
        return all.getString("authz").replace("{pub}", key)
    }
}
